version: 0.0
os: linux
files:
  - source: /config/basic.json
    destination: /tmp/
  - source: /config/prometheus.yml
    destination: /tmp/
  - source: /packages/consul_0.6.4_linux_amd64.zip
    destination: /tmp/
  - source: /packages/consul_0.6.4_web_ui.zip
    destination: /tmp/
  - source: /packages/consul-template_0.14.0_linux_amd64.zip
    destination: /tmp/
  - source: /scripts/debug.sh
    destination: /home/ubuntu/
permissions:
  - object: /tmp/basic.json
    owner: ubuntu
    group: users
    mode: 644
  - object: /tmp/prometheus.yml
    owner: ubuntu
    group: users
    mode: 644
  - object: /home/ubuntu/debug.sh
    owner: ubuntu
    group: ubuntu
    mode: 744
hooks:
  AfterInstall:
    - location: scripts/mesos_master_install.sh
      timeout: 300
      runas: root
    - location: scripts/consul_server_install.sh
      timeout: 300
      runas: root
