version: 0.0
os: linux
files:
  - source: /config/basic.json
    destination: /tmp/
  - source: /config/prometheus.yml
    destination: /tmp/
  - source: /scripts/debug.sh
    destination: /home/ubuntu/
permissions:
  - object: /home/ubuntu/debug.sh
    owner: ubuntu
    group: users
    mode: 744
hooks:
  AfterInstall:
    - location: scripts/mesos_master_install.sh
      timeout: 300
      runas: root
