version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /config/basic.json
    destination: /tmp/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
    - location: /scripts/remove_stuff
      timeout: 300
      runas: root
    - location: scripts/mesos_master_install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

