version: 0.0
os: linux
files:
  - source: /config/basic.json
    destination: /tmp/
  - source: /config/prometheus.yml
    destination: /tmp/
  - source: /packages/vault_0.5.2_linux_amd64.zip
    destination: /tmp/
  - source: /scripts/debug.sh
    destination: /home/ubuntu/
  - source: /packages/mesos-dns-v0.5.2-linux-amd64
    destination: /usr/bin/
permissions:
  - object: /tmp/basic.json
    owner: ubuntu
    group: users
    mode: 644
  - object: /tmp/prometheus.yml
    owner: ubuntu
    group: users
    mode: 644
  - object: /home/ubuntu/debug.sh
    owner: ubuntu
    group: ubuntu
    mode: 744
  - object: /usr/bin/mesos-dns-v0.5.2-linux-amd64
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/docker_install.sh
      timeout: 300
      runas: root
    - location: scripts/mesos_master_install.sh
      timeout: 300
      runas: root
    - location: scripts/vault.sh
      timeout: 300
      runas: root
    - location: scripts/dns-services.sh
      timeout: 300
      runas: root
    - location: scripts/docker_prebuild.sh
      timeout: 300
      runas: root
    - location: scripts/cluster_settings.sh
      timeout: 300
      runas: root
